package libxml2

import (
	"github.com/goplus/llgo/c"
	"unsafe"
)

//go:linkname InitGlobals C.xmlInitGlobals
func InitGlobals()

//go:linkname CleanupGlobals C.xmlCleanupGlobals
func CleanupGlobals()

// llgo:type C
type ParserInputBufferCreateFilenameFunc func(*int8, CharEncoding) ParserInputBufferPtr

// llgo:type C
type OutputBufferCreateFilenameFunc func(*int8, CharEncodingHandlerPtr, c.Int) OutputBufferPtr

//go:linkname ParserInputBufferCreateFilenameDefault C.xmlParserInputBufferCreateFilenameDefault
func ParserInputBufferCreateFilenameDefault(func_ ParserInputBufferCreateFilenameFunc) ParserInputBufferCreateFilenameFunc

//go:linkname OutputBufferCreateFilenameDefault C.xmlOutputBufferCreateFilenameDefault
func OutputBufferCreateFilenameDefault(func_ OutputBufferCreateFilenameFunc) OutputBufferCreateFilenameFunc

// llgo:type C
type RegisterNodeFunc func(NodePtr)

// llgo:type C
type DeregisterNodeFunc func(NodePtr)

type X_xmlGlobalState struct {
	XmlParserVersion                        *int8
	XmlDefaultSAXLocator                    SAXLocator
	XmlDefaultSAXHandler                    SAXHandlerV1
	DocbDefaultSAXHandler                   SAXHandlerV1
	HtmlDefaultSAXHandler                   SAXHandlerV1
	XmlFree                                 unsafe.Pointer
	XmlMalloc                               unsafe.Pointer
	XmlMemStrdup                            unsafe.Pointer
	XmlRealloc                              unsafe.Pointer
	XmlGenericError                         unsafe.Pointer
	XmlStructuredError                      unsafe.Pointer
	XmlGenericErrorContext                  unsafe.Pointer
	OldXMLWDcompatibility                   c.Int
	XmlBufferAllocScheme                    BufferAllocationScheme
	XmlDefaultBufferSize                    c.Int
	XmlSubstituteEntitiesDefaultValue       c.Int
	XmlDoValidityCheckingDefaultValue       c.Int
	XmlGetWarningsDefaultValue              c.Int
	XmlKeepBlanksDefaultValue               c.Int
	XmlLineNumbersDefaultValue              c.Int
	XmlLoadExtDtdDefaultValue               c.Int
	XmlParserDebugEntities                  c.Int
	XmlPedanticParserDefaultValue           c.Int
	XmlSaveNoEmptyTags                      c.Int
	XmlIndentTreeOutput                     c.Int
	XmlTreeIndentString                     *int8
	XmlRegisterNodeDefaultValue             unsafe.Pointer
	XmlDeregisterNodeDefaultValue           unsafe.Pointer
	XmlMallocAtomic                         unsafe.Pointer
	XmlLastError                            Error
	XmlParserInputBufferCreateFilenameValue unsafe.Pointer
	XmlOutputBufferCreateFilenameValue      unsafe.Pointer
	XmlStructuredErrorContext               unsafe.Pointer
}
type GlobalState X_xmlGlobalState
type GlobalStatePtr *GlobalState

//go:linkname InitializeGlobalState C.xmlInitializeGlobalState
func InitializeGlobalState(gs GlobalStatePtr)

//go:linkname ThrDefSetGenericErrorFunc C.xmlThrDefSetGenericErrorFunc
func ThrDefSetGenericErrorFunc(ctx unsafe.Pointer, handler GenericErrorFunc)

//go:linkname ThrDefSetStructuredErrorFunc C.xmlThrDefSetStructuredErrorFunc
func ThrDefSetStructuredErrorFunc(ctx unsafe.Pointer, handler StructuredErrorFunc)

//go:linkname RegisterNodeDefault C.xmlRegisterNodeDefault
func RegisterNodeDefault(func_ RegisterNodeFunc) RegisterNodeFunc

//go:linkname ThrDefRegisterNodeDefault C.xmlThrDefRegisterNodeDefault
func ThrDefRegisterNodeDefault(func_ RegisterNodeFunc) RegisterNodeFunc

//go:linkname DeregisterNodeDefault C.xmlDeregisterNodeDefault
func DeregisterNodeDefault(func_ DeregisterNodeFunc) DeregisterNodeFunc

//go:linkname ThrDefDeregisterNodeDefault C.xmlThrDefDeregisterNodeDefault
func ThrDefDeregisterNodeDefault(func_ DeregisterNodeFunc) DeregisterNodeFunc

//go:linkname ThrDefOutputBufferCreateFilenameDefault C.xmlThrDefOutputBufferCreateFilenameDefault
func ThrDefOutputBufferCreateFilenameDefault(func_ OutputBufferCreateFilenameFunc) OutputBufferCreateFilenameFunc

//go:linkname ThrDefParserInputBufferCreateFilenameDefault C.xmlThrDefParserInputBufferCreateFilenameDefault
func ThrDefParserInputBufferCreateFilenameDefault(func_ ParserInputBufferCreateFilenameFunc) ParserInputBufferCreateFilenameFunc

//go:linkname X__docbDefaultSAXHandler C.__docbDefaultSAXHandler
func X__docbDefaultSAXHandler() *SAXHandlerV1

//go:linkname X__htmlDefaultSAXHandler C.__htmlDefaultSAXHandler
func X__htmlDefaultSAXHandler() *SAXHandlerV1

//go:linkname X__xmlLastError C.__xmlLastError
func X__xmlLastError() *Error

/*
 * Everything starting from the line below is
 * Automatically generated by build_glob.py.
 * Do not modify the previous line.
 */
//go:linkname X__oldXMLWDcompatibility C.__oldXMLWDcompatibility
func X__oldXMLWDcompatibility() *c.Int

//go:linkname X__xmlBufferAllocScheme C.__xmlBufferAllocScheme
func X__xmlBufferAllocScheme() *BufferAllocationScheme

// llgo:link BufferAllocationScheme.ThrDefBufferAllocScheme C.xmlThrDefBufferAllocScheme
func (recv_ BufferAllocationScheme) ThrDefBufferAllocScheme() BufferAllocationScheme {
	return 0
}

//go:linkname X__xmlDefaultBufferSize C.__xmlDefaultBufferSize
func X__xmlDefaultBufferSize() *c.Int

//go:linkname ThrDefDefaultBufferSize C.xmlThrDefDefaultBufferSize
func ThrDefDefaultBufferSize(v c.Int) c.Int

//go:linkname X__xmlDefaultSAXHandler C.__xmlDefaultSAXHandler
func X__xmlDefaultSAXHandler() *SAXHandlerV1

//go:linkname X__xmlDefaultSAXLocator C.__xmlDefaultSAXLocator
func X__xmlDefaultSAXLocator() *SAXLocator

//go:linkname X__xmlDoValidityCheckingDefaultValue C.__xmlDoValidityCheckingDefaultValue
func X__xmlDoValidityCheckingDefaultValue() *c.Int

//go:linkname ThrDefDoValidityCheckingDefaultValue C.xmlThrDefDoValidityCheckingDefaultValue
func ThrDefDoValidityCheckingDefaultValue(v c.Int) c.Int

//go:linkname X__xmlGenericError C.__xmlGenericError
func X__xmlGenericError() GenericErrorFunc

//go:linkname X__xmlStructuredError C.__xmlStructuredError
func X__xmlStructuredError() StructuredErrorFunc

//go:linkname X__xmlGenericErrorContext C.__xmlGenericErrorContext
func X__xmlGenericErrorContext() *unsafe.Pointer

//go:linkname X__xmlStructuredErrorContext C.__xmlStructuredErrorContext
func X__xmlStructuredErrorContext() *unsafe.Pointer

//go:linkname X__xmlGetWarningsDefaultValue C.__xmlGetWarningsDefaultValue
func X__xmlGetWarningsDefaultValue() *c.Int

//go:linkname ThrDefGetWarningsDefaultValue C.xmlThrDefGetWarningsDefaultValue
func ThrDefGetWarningsDefaultValue(v c.Int) c.Int

//go:linkname X__xmlIndentTreeOutput C.__xmlIndentTreeOutput
func X__xmlIndentTreeOutput() *c.Int

//go:linkname ThrDefIndentTreeOutput C.xmlThrDefIndentTreeOutput
func ThrDefIndentTreeOutput(v c.Int) c.Int

//go:linkname X__xmlTreeIndentString C.__xmlTreeIndentString
func X__xmlTreeIndentString() **int8

//go:linkname ThrDefTreeIndentString C.xmlThrDefTreeIndentString
func ThrDefTreeIndentString(v *int8) *int8

//go:linkname X__xmlKeepBlanksDefaultValue C.__xmlKeepBlanksDefaultValue
func X__xmlKeepBlanksDefaultValue() *c.Int

//go:linkname ThrDefKeepBlanksDefaultValue C.xmlThrDefKeepBlanksDefaultValue
func ThrDefKeepBlanksDefaultValue(v c.Int) c.Int

//go:linkname X__xmlLineNumbersDefaultValue C.__xmlLineNumbersDefaultValue
func X__xmlLineNumbersDefaultValue() *c.Int

//go:linkname ThrDefLineNumbersDefaultValue C.xmlThrDefLineNumbersDefaultValue
func ThrDefLineNumbersDefaultValue(v c.Int) c.Int

//go:linkname X__xmlLoadExtDtdDefaultValue C.__xmlLoadExtDtdDefaultValue
func X__xmlLoadExtDtdDefaultValue() *c.Int

//go:linkname ThrDefLoadExtDtdDefaultValue C.xmlThrDefLoadExtDtdDefaultValue
func ThrDefLoadExtDtdDefaultValue(v c.Int) c.Int

//go:linkname X__xmlParserDebugEntities C.__xmlParserDebugEntities
func X__xmlParserDebugEntities() *c.Int

//go:linkname ThrDefParserDebugEntities C.xmlThrDefParserDebugEntities
func ThrDefParserDebugEntities(v c.Int) c.Int

//go:linkname X__xmlParserVersion C.__xmlParserVersion
func X__xmlParserVersion() **int8

//go:linkname X__xmlPedanticParserDefaultValue C.__xmlPedanticParserDefaultValue
func X__xmlPedanticParserDefaultValue() *c.Int

//go:linkname ThrDefPedanticParserDefaultValue C.xmlThrDefPedanticParserDefaultValue
func ThrDefPedanticParserDefaultValue(v c.Int) c.Int

//go:linkname X__xmlSaveNoEmptyTags C.__xmlSaveNoEmptyTags
func X__xmlSaveNoEmptyTags() *c.Int

//go:linkname ThrDefSaveNoEmptyTags C.xmlThrDefSaveNoEmptyTags
func ThrDefSaveNoEmptyTags(v c.Int) c.Int

//go:linkname X__xmlSubstituteEntitiesDefaultValue C.__xmlSubstituteEntitiesDefaultValue
func X__xmlSubstituteEntitiesDefaultValue() *c.Int

//go:linkname ThrDefSubstituteEntitiesDefaultValue C.xmlThrDefSubstituteEntitiesDefaultValue
func ThrDefSubstituteEntitiesDefaultValue(v c.Int) c.Int

//go:linkname X__xmlRegisterNodeDefaultValue C.__xmlRegisterNodeDefaultValue
func X__xmlRegisterNodeDefaultValue() RegisterNodeFunc

//go:linkname X__xmlDeregisterNodeDefaultValue C.__xmlDeregisterNodeDefaultValue
func X__xmlDeregisterNodeDefaultValue() DeregisterNodeFunc

//go:linkname X__xmlParserInputBufferCreateFilenameValue C.__xmlParserInputBufferCreateFilenameValue
func X__xmlParserInputBufferCreateFilenameValue() ParserInputBufferCreateFilenameFunc

//go:linkname X__xmlOutputBufferCreateFilenameValue C.__xmlOutputBufferCreateFilenameValue
func X__xmlOutputBufferCreateFilenameValue() OutputBufferCreateFilenameFunc
